### ISSUE TITLE
MediaPicker doesn't work with new Android 5.1.1 security.

### ISSUE THREAD

**Issue by scastria** [xamarin/Xamarin.Mobile#48]
With Android 5.1.1, only the Activity that launches the photo library intent has permission to read the content:// Uri that it returns when a user selects a photo.  Since the MediaPicker component has an internal MediaPickerActivity that actually launches the photo library intent instead of the calling app, only the MediaPickerActivity can read the Uri.  Currently, MediaPickerActivity just forwards the content Uri back to the calling app which results in a security exception on Android 5.1.1.

My proposal is to change the GetPickPhotoUI method to accept options just like the GetTakePhotoUI does.  The user can pass in a Name and Directory where he wants the selected photo to be copied to.  Then when the MediaPickerActivity receives the content Uri, it can read that Uri (since it is the only thing that has permission to do so) and copy it to the user specified file path.  Then that file path is returned back to the calling app Activity.

**Comment by jamesmontemagno** [comment]
I have a fix in my media plugin here to run an initial copy on the activityresult: 
https://github.com/jamesmontemagno/Xamarin.Plugins/commit/611af3cde5be8c88feacfc55bbdb25a72ec365f7

The issue is a change from here as described: http://stackoverflow.com/questions/30572261/using-data-from-context-providers-or-requesting-google-photos-read-permission

**Comment by jamesmontemagno** [comment]
I have finished  a full implementation. I will do a PR for xamarin.mobile.
