### ISSUE TITLE
Conflict between Xamarin.Mobile and Xamarin.iOS

### ISSUE THREAD

**Issue by devpedrofranco** [xamarin/Xamarin.Mobile#65]
Including Xamarin.Mobile in PCL iOS project got this error:

Add reference manualy:
> Cannot reference 'monotouch.dll' in a Xamarin.iOS project - it is implicitly referenced by 'Xamarin.Mobile, Version=0.7.1.0, Culture=neutral, PublicKeyToken=null'

From NuGet:

> Could not install package 'xamstore-xamarin.mobile 0.7.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by kislayraj** [comment]
i am getting the same issue

**Comment by Cheesebaron** [comment]
I suggest you use a Plugin for the wanted functionality instead of using Xamarin.Mobile.

- Geolocation: https://www.nuget.org/packages/Xam.Plugin.Geolocator/3.0.4
- Media: https://www.nuget.org/packages/Xam.Plugin.Media/2.6.2
- Contacts: https://www.nuget.org/packages/Xam.Plugin.Contacts/2.2.0.37-beta

There are many more if you search for Xamarin Plugin on NuGet.

I would consider this project obsolete and replaced by the plugins.

**Comment by devpedrofranco** [comment]
I solved this problem installing the Xamarin.Mobile on IOS in Components instead of NuGet

**Comment by agat366** [comment]
Xamarin Components are no longer supported by Visual Studio starting from v15.6.
